### ISSUE TITLE
[BUG] Splat.DryIoc UseDryIocDependencyResolver throws NullReferenceException in ViewStackServiceBase ctor

### ISSUE THREAD

**Issue by xplatsolutions** [reactiveui/Sextant#139]
Having the below setup in AppBootstrapper.cs.

```
public static string NavigationViewKey => nameof(NavigationView);

container.Register<IViewFor<MainViewModel>, MainView>();
container.Register<IViewFor<ReceivedViewModel>, ReceivedView>();
container.Register<MainViewModel>();
container.Register<ReceivedViewModel>();
container.Register<ICache, Cache>(Reuse.Singleton);
container.Register<IApiService, ApiService>(Reuse.Singleton);

// Sextant
container.RegisterDelegate<NavigationView>(p => new NavigationView(RxApp.MainThreadScheduler, RxApp.TaskpoolScheduler, ViewLocator.Current), Reuse.Singleton, serviceKey: NavigationViewKey);
var navigationView = container.Resolve<NavigationView>(NavigationViewKey);
container.RegisterDelegate<IParameterViewStackService>(p => new ParameterViewStackService(navigationView), Reuse.Singleton);

container.UseDryIocDependencyResolver(); // Throws NullReferenceException
```

**Steps To Reproduce**
1. Add Splat.DryIoc
2. Register Sextant services (NavigationView, ParameterViewStackService) using a DryIoc Container instance
3. Invoke container.UseDryIocDependencyResolver();

**Expected behavior**
No exception should be thrown and Splat Locator.Current should return the desired service e.g. NavigationView.

**Environment**
- OS:       Reproduced in iOS Xr 12.4 simulator and Android Nexus 5 Oreo 8.0 emulator

**Additional context**
Stacktrace:

>   at Sextant.ViewStackServiceBase..ctor (Sextant.IView view) [0x0003f] in <18a2a99228334d44a1fc881b86fd2f3f>:0 
>   at Sextant.ParameterViewStackService..ctor (Sextant.IView view) [0x00000] in <18a2a99228334d44a1fc881b86fd2f3f>:0 
>   at Sextant.DependencyResolverMixins+<>c__DisplayClass2_0.<RegisterViewStackService>b__0 () [0x00000] in <18a2a99228334d44a1fc881b86fd2f3f>:0 
>   at Splat.DependencyResolverMixins+<>c__DisplayClass8_0`1[T].<RegisterLazySingleton>b__0 () [0x00000] in <5df94a01943e4dbb8c7558db0cbc5282>:0 
>   at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:333 
>   at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:351 
>   at System.Lazy`1[T].CreateValue () [0x00074] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:431 
>   at System.Lazy`1[T].get_Value () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:509 
>   at Splat.DependencyResolverMixins+<>c__DisplayClass7_0.<RegisterLazySingleton>b__0 () [0x00000] in <5df94a01943e4dbb8c7558db0cbc5282>:0 
>   at Splat.DryIoc.DryIocDependencyResolver.Register (System.Func`1[TResult] factory, System.Type serviceType, System.String contract) [0x00008] in <d1de9cc27aba45b2acb684b910c220c4>:0 
>   at Splat.DependencyResolverMixins.RegisterLazySingleton (Splat.IMutableDependencyResolver resolver, System.Func`1[TResult] valueFactory, System.Type serviceType, System.String contract) [0x00013] in <5df94a01943e4dbb8c7558db0cbc5282>:0 
>   at Splat.DependencyResolverMixins.RegisterLazySingleton[T] (Splat.IMutableDependencyResolver resolver, System.Func`1[TResult] valueFactory, System.String contract) [0x0000d] in <5df94a01943e4dbb8c7558db0cbc5282>:0 
>   at Sextant.DependencyResolverMixins.RegisterViewStackService (Splat.IMutableDependencyResolver dependencyResolver) [0x0001b] in <18a2a99228334d44a1fc881b86fd2f3f>:0 
>   at Sextant.SextantExtensions.Initialize (Sextant.Sextant sextant) [0x0000b] in <18a2a99228334d44a1fc881b86fd2f3f>:0 
>   at Sextant.Sextant+<>c.<.cctor>b__1_0 () [0x0000d] in <18a2a99228334d44a1fc881b86fd2f3f>:0 
>   at Splat.InternalLocator.SetLocator (Splat.IDependencyResolver dependencyResolver) [0x00050] in <5df94a01943e4dbb8c7558db0cbc5282>:0 
>   at Splat.Locator.SetLocator (Splat.IDependencyResolver dependencyResolver) [0x00005] in <5df94a01943e4dbb8c7558db0cbc5282>:0 
>   at Splat.DryIoc.SplatDryIocExtensions.UseDryIocDependencyResolver (DryIoc.IContainer container) [0x00006] in <d1de9cc27aba45b2acb684b910c220c4>:0 
>   at Eight.Influencers.AppBootstrapper..ctor (DryIoc.Container container) [0x000f4] in /Users/georgiostaskos/Documents/Projects/WeAre8/eight.influencers.forms/src/Eight.Influencers/Eight.Influencers/AppBootstrapper.cs:40 
>   at Eight.Influencers.App..ctor (DryIoc.Container container) [0x00059] in /Users/georgiostaskos/Documents/Projects/WeAre8/eight.influencers.forms/src/Eight.Influencers/Eight.Influencers/App.xaml.cs:31 
>   at Eight.Influencers.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x0000d] in /Users/georgiostaskos/Documents/Projects/WeAre8/eight.influencers.forms/src/Eight.Influencers/Eight.Influencers.iOS/AppDelegate.cs:34 
>   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
>   at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
>   at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
>   at Eight.Influencers.iOS.Application.Main (System.String[] args) [0x00001] in /Users/georgiostaskos/Documents/Projects/WeAre8/eight.influencers.forms/src/Eight.Influencers/Eight.Influencers.iOS/Main.cs:17

**Comment by RLittlesII** [comment]
I had a chance to look at this over the weekend.  Seems this is not a bug with Splat.DryIoc or Sextant.  Unless it has been inadvertently fixed through changes since the time this bug was reported.

The following information on DryIoc Documentation on [Register and Resolve](https://bitbucket.org/dadhi/dryioc/wiki/RegisterResolve.md)

> Though powerful, registering delegate may lead to the problems:
    Memory leaks by capturing variables into delegate closure and keeping them for a container lifetime.
    Delegate is the black box for Container - which makes hard to find type mismatches or diagnose other potential problems.
Therefore, try to use it only as last resort. DryIoc has plenty of tools to cover for custom delegate in more effective way. The ultimate alternative would be Factory Methods.

A working example of Sextant using Splat.DryIoc can be found https://github.com/RLittlesII/Reactive.Sandbox/tree/master/xamarin/forms/Sextant139

![Sextant 139](https://user-images.githubusercontent.com/6969701/71841346-cbb9f700-3084-11ea-80b0-cb842f9ea1a7.gif)
