### ISSUE TITLE
feature: Add navigation for AvaloniaUI

### ISSUE THREAD

**Issue by alexislom** [reactiveui/Sextant#164]
I've also read this amazing post https://kent-boogaart.com/blog/custom-routing-in-reactiveui from Kent, but I have a project with desktop platforms (windows and linux) and mobile platform (android), and I would like to use one model and viewmodel layer with AvaloniaUI and Xamarin for UI and ReactiveUI like MVVM. But I don't want to write custom navigation for avalonia in reactive style.

Could you please add this functionality?

**Comment by glennawatson** [comment]
Avalonia usually do their own reactiveui plugins so best to ask them.
