### ISSUE TITLE
feature: Master Detail Support For Xamarin Forms

### ISSUE THREAD

**Issue by albilaga** [reactiveui/Sextant#169]
**Is your feature request related to a problem? Please describe.**
I'm confused how I do navigation using Sextant with Xamarin Forms. Master Detail usually have Navigation Page as root in detail but right now we can't (or I don't know how to) navigate between detail in Master Detail

**Describe the solution you'd like**
Maybe we can take a look how navigation used in default routing from ReactiveUI https://github.com/reactiveui/ReactiveUI.Samples/tree/master/xamarin-forms/MasterDetail/MasterDetail ?

**Comment by RLittlesII** [comment]
@albilaga I'll put together a Sextant sample for Master Detail.  If that feels too cumbersome, I'll look into a true `MasterDetailPage` implementation.

**Comment by thor089** [comment]
Hi
Any news on this topic?
I would appreciate a small sample.
e.g. a master, 2 details inkl. going back.
Somehow I struggle a bit. ;-)

**Comment by RLittlesII** [comment]
https://github.com/RLittlesII/ReactiveUI.Showroom/pull/5 has **_an_** example of how to implement Master-Detail using Sextant.
