### ISSUE TITLE
[BUG] PopRootAndTick in ViewStackServiceBase leaves behind the wrong viewmodel

### ISSUE THREAD

**Issue by limefrogyank** [reactiveui/Sextant#189]
**Describe the bug**

If you look at `PopRootAndTick` in `ViewStackServiceBase` found here, https://github.com/reactiveui/Sextant/blob/master/src/Sextant/Navigation/ViewStackServiceBase.cs#L218 , I believe the code is returning a stack with the wrong viewmodel in it.

The purpose of this method is to clean up the stack **after** navigation to the root has occurred.  When `PopToRootPage` is called by a developer, an observable on the View (NavigationView) is sent a signal, then the method in question is called via a `Do()` following the observable.

The `stackSubject.OnNext()` should just update the stack by passing in a list with only the root viewmodel in it.  **But it doesn't.**   This line is the problem:
```
poppedStack = stack.RemoveRange(stack.IndexOf(stack[0]), stack.Count - 1)
```  
To me, that looks like it takes the stack, removes everything but the last item in the list, and returns that modified list.

Second, I think there might be a problem with the reactive stuff:
```
stackSubject.Take(stackSubject.Value.Count - 1)
```
This doesn't make sense to me.  The stackSubject is an observable of a list of viewmodels, not an observable of viewmodel.  We just want to grab the latest list `Take(1)`... and even this is not necessary since we could just grab `stackSubject.Value`.  

Ultimately, I've only tried this on Xamarin.Forms Android, **but** you'll never see the consequences of this bug because the system doesn't rely on the first item in the stack after it's been placed during initialization.  

**Steps To Reproduce**
I made a branch on my repo that sticks an extra button Home to display the current viewmodel type.  If you navigate forward a few times (red view), then pop to root, the top of the stack will contain a RedViewModel type instead of HomeViewModel type.
https://github.com/limefrogyank/Sextant/tree/PopRootAndTick_Bug

**Expected behavior**
Should contain HomeViewModel type.

**Screenshots**
Initial TopPage():
![Screenshot_1578074523](https://user-images.githubusercontent.com/7821384/71740198-75448280-2e10-11ea-94ff-5d367c614d8d.png)

After navigating to red page a few times in a row, then hitting pop to root:
![Screenshot_1578074538](https://user-images.githubusercontent.com/7821384/71740238-8ab9ac80-2e10-11ea-91c6-d8b7fe6b19f9.png)

**Environment**

- OS:       Windows10
- Device:   Android Emulator
- Version:  
- Working Version: 

**Additional context**

**Comment by RLittlesII** [comment]
@limefrogyank Thanks for reporting this.  I had some other issues that I resolved on Xamarin.iOS around `PopToRoot` not too long ago.  I will look into this and see if we can find a resolution.
The thought behind removing is to try and leave **a** ViewModel on the stack.

Is this really specific to Xamarin.Forms Android?  I will try and reproduce it on iOS to be safe, as that seems an odd side effect.

**Comment by limefrogyank** [comment]
I don’t have easy access to testing on iOS so I don’t know.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by RLittlesII** [comment]
@limefrogyank So I am trying to reproduce this, but no matter how many Red Pages I push on iOS, I don't see the problem.  I have a branch [GH189](https://github.com/reactiveui/Sextant/tree/gh189) where I am reproducing this.  Can you verify that this code still produces an error on your side?  I am moving to test Android now, just want to be sure my reproduction is correct.

**Comment by limefrogyank** [comment]
Looks correct to me.

You’re right, I can’t reproduce it either.  I need to compare yours to mine and see what happened.

Lee

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by limefrogyank** [comment]
Oh, you've got the changes I made already put into your branch.  The original code for `PopRootAndTick` was this:
```
IImmutableList<T> poppedStack = ImmutableList<T>.Empty;

            if (stackSubject?.Value == null || !stackSubject.Value.Any())
            {
                throw new InvalidOperationException("Stack is empty.");
            }

            stackSubject
                .Take(stackSubject.Value.Count - 1)
                .Where(stack => stack != null)
                .Subscribe(stack => poppedStack = stack.RemoveRange(stack.IndexOf(stack[0]), stack.Count - 1));

            stackSubject.OnNext(poppedStack);
```

**Comment by RLittlesII** [comment]
That means your code somehow made it to the master branch, as my branch is cut from the most recent master.

**Comment by RLittlesII** [comment]
@limefrogyank Can you verify master is fixed?  Then I would argue we can close this and attach it to the PR that solved the problem.

**Comment by limefrogyank** [comment]
This works fine for me.  Sorry to slip that in unnoticed.  

Fixed with https://github.com/reactiveui/Sextant/commit/dc23331447796cd5b209c185ebcee1492b78a0d1

Right?

**Comment by RLittlesII** [comment]
Yes.  No worries about it.  It was a big PR with a lot of files changed.  Appreciate the contribution!
