### ISSUE TITLE
[BUG] navigationService.PopPage does not trigger WhenNavigatedTo

### ISSUE THREAD

**Issue by thor089** [reactiveui/Sextant#190]
**Describe the bug**
When navigating to a view model with 

` var navigationService = Locator.Current.GetService<IParameterViewStackService>();
            return navigationService
                            .PushPage(new TimeTrackingDetailPageViewModel(), new NavigationParameter { { "parameter", "test" } });`

WhenNavigatedTo is triggered and you can read the parameter.

`navigationService
                            .PopPage(new NavigationParameter { { "parameter", "back" } });`

Does not trigger WhenNavigatedTo and you are not able to retrieve the parameter 

**Steps To Reproduce**
1. Take the "Navigation.Parameters" sample - https://github.com/reactiveui/ReactiveUI.Samples/tree/master/xamarin-forms/Navigation.Parameters

2. Extend the ReceivedViewModel to have a command which calls the "PopPage(...)"

3. Override WhenNavigatingTo in PassViewModel

**Expected behavior**
WhenNavigatingTo should always be called when navigating to a view model

**Environment**
- OS:       Android: Emulator (Oreo); iOS Simulator iPhone 11 - 13.3

**Comment by RLittlesII** [comment]
@thor089 Thanks for reporting this.  I will probably work a fix in this weekend.

**Comment by thor089** [comment]
@RLittlesII that would be gorgeous. If you need someone to test - just let me know.

**Comment by thor089** [comment]
@RLittlesII: Thank you very much!
I verified it with iOS and Android and it is working now.
Looking forward to the next release.

**Comment by RLittlesII** [comment]
Once it gets merged in there should be a release early next week.
