### ISSUE TITLE
[BUG] Allow ViewModelFactory to resolve Views with contracts

### ISSUE THREAD

**Issue by AlexanderMelchers** [reactiveui/Sextant#230]
**Describe the bug**
When navigating using [`PushPage<TViewModel>(string? contract = null, bool resetStack = false, bool animate = true)`](https://github.com/reactiveui/Sextant/blob/4467e350e1525d8194dccb7efd47c58f3e0536ae/src/Sextant/Navigation/ViewStackServiceBase.cs#L131), the passed `contract` is only used to resolve the view to use with the `TViewModel`, but not the view model itself.

**Steps To Reproduce**
Provide the steps to reproduce the behavior:
1. Create a view model and accompanying view
2. Register the view with the `Locator` for use with the view model
3. Register two versions of the view model with the `Locator` under two different contracts; make sure these contracts affect the way the view model is rendered into the view (e.g. label-text)
3. Set up navigation with a main page and two buttons
4. Configure the buttons to open the view/view model, each with a different view model contract.

**Expected behavior**
- The view models can be resolved by their contract, resulting in two different renderings of the view.
- Views can be resolved by a separate contract.
- In practice, the view models can't be resolved by contract.

**Environment**
- OS:       Android, iOS
- Device:   any
- Version:   2.5.8
- Working Version: none, as to my knowledge

**Additional context**
1. @winterdouglas originally mentioned this problem to me, as something he had run into.
2. When implementing the `IPopupViewStackService` in our app, as mentioned in #76, I noticed that I could not instantiate view models based on their contact. That is, in my scenario, I needed to have multiple expressions of the same view model to render in the same view (one to many relationship from view to view model).
3. Because of 2, I noticed that in `ViewStackServiceBase` the contract was not being used when resolving/instantiating the view model (see [here](https://github.com/reactiveui/Sextant/blob/4467e350e1525d8194dccb7efd47c58f3e0536ae/src/Sextant/Navigation/ViewStackServiceBase.cs#L134)).
4. Even if 3 were to be resolved by passing the contract along to `ViewModelFactory.Current.Create<TViewModel>()`, view resolution might next fail, because - in my case - I'd have one view for multiple contracted/instances of the view models. Suggest to change the signature of [`PushPage<TViewModel>(string? contract = null, bool resetStack = false, bool animate = true)`](https://github.com/reactiveui/Sextant/blob/4467e350e1525d8194dccb7efd47c58f3e0536ae/src/Sextant/Navigation/ViewStackServiceBase.cs#L131) to split up the contract into a `viewModelContract` and a `viewContract` as such: `PushPage<TViewModel>(string? viewModelContract = null, string? viewContract = null, bool resetStack = false, bool animate = true)`.
5. The problem described at 4 exists for other method-signatures as well, for example [`PushModal<TViewModel>(string? contract = null, bool withNavigationPage = true)`](https://github.com/reactiveui/Sextant/blob/4467e350e1525d8194dccb7efd47c58f3e0536ae/src/Sextant/Navigation/ViewStackServiceBase.cs#L123), which does resolve the view model correctly by contract, but forces view model and view to both be registered under the same contracts, potentially requiring unnecessary additional registrations.

**Comment by RLittlesII** [comment]
I believe I understand your points.  I am not 100% sure that was considered when the feature was done.  It was added as a simple fix for a need @winterdouglas, and I hadn't heard from him that it was insufficient.

I am going to change this to a feature request and make sure that I understand the use cases this needs to address.  The title change is for tracking, not that it would be prioritized any differently.

**Comment by AlexanderMelchers** [comment]
Sure thing! You can also have a look at the service implementation I added to #76, as this is where I changed the code to work as I meant to express it above. Also, don't hesitate to ask: I'll be happy to clarify things where I can :)
