### ISSUE TITLE
Apps With a Splash Page?

### ISSUE THREAD

**Issue by NightOwlCoder** [reactiveui/Sextant#242]
Hey there guys,

I'm learning ReactiveUI/Sextant and started creating an app based on it.

Our app has a Splash Page, that will after some validation navigate to the Login page or Dashboard.

I'm following the examples and it is working fine, aside from the fact that the splash page has a "Navigation Bar" that we really do not want....

My best guess is that the bar comes from this:
`MainPage = Locator.Current.GetNavigationView();`

But I can't find another way to actually start my app if not by the above sentence.

Can someone please guide me here?

Thanks

**Comment by glennawatson** [comment]
Your probably better off joining the rxui slack chat, and joining the #sextant channel. https://www.reactiveui.net/slack

**Comment by RLittlesII** [comment]
@NightOwlCoder Are you using XAML or C#?

In Xamarin.Forms every `ContentPage` has access the the `NavigationPage` which is responsible for its navigation.  If you do not want the navigation bar to display on a given page, you turn it off on that page by accessing the `NavigationPage` static.

```xml
<xamForms:ReactiveContentPage x:TypeArguments="splash:SplashViewModel" xmlns="http://xamarin.com/schemas/2014/forms"
                              xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                              xmlns:xamForms="clr-namespace:ReactiveUI.XamForms;assembly=ReactiveUI.XamForms"
                              xmlns:splash="clr-namespace:Splash.Splash;assembly=Splash"
                              x:Class="Splash.Splash.SplashPage"
                              NavigationPage.HasNavigationBar="False">
```

```csharp

        public SplashPage()
        {
            NavigationPage.SetHasNavigationBar(this, false);
            InitializeComponent();
        }
```

**Comment by NightOwlCoder** [comment]
It is my first project actually doing C# only.
I'm more of a XAML guy, but wanted to test the waters with it.

So far, after learning about `Xamarin.Forms C# markup`, I'm actually liking it.

And thank you for the code above, worked flawlessly.

**Comment by RLittlesII** [comment]
Glad it solved your issue.  There are some upcoming changes that will be happening that should make it easier to manipulate the titles and such.
