### ISSUE TITLE
feature: Add support for Avalonia

### ISSUE THREAD

**Issue by worldbeater** [reactiveui/Sextant#252]
**Is your feature request related to a problem? Please describe.**

There is no Avalonia support.

**Describe the solution you'd like**

Would be happy to see Sextant+Avalonia becoming great friends.

**Describe alternatives you've considered**

For now, we have a `RoutedViewHost` and stuff living in the `Avalonia.ReactiveUI` package https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.ReactiveUI
So probably the classes from that package may shed some light on how to implement a `NavigationView`.

**Describe suggestions on how to achieve the feature**

Probably we could build and ship a new `Sextant.Avalonia` package supporting latest Avalonia NuGet release. Or, we could start the discussion on the Avalonia side, and contribute Sextant support directly into their repository. Not sure which option would be a better one...

**Comment by glennawatson** [comment]
Avalonia nav and wpf nav probably are fairly similar to each other. Eg each would require their own navigation stack.

**Comment by RLittlesII** [comment]
I think it's achievable. WPF is near the top of the list for platforms to support.

I would love to work with you to define how Sextant.Avalonia would work.
