### ISSUE TITLE
feature: Add support for passing navigation parameters

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/Sextant#40]

**Comment by gsgou** [comment]
@RLittlesII i want to use this feature in an active project.
Can i expect soon a new github nuget Release with this feature only?
Otherwise i will have to add this project as submodule.

**Comment by glennawatson** [comment]
You can use it right now with the MyGet NuGet source 

Configure visual studio to use the following address https://www.myget.org/F/reactiveui/api/v3/index.json

**Comment by glennawatson** [comment]
Any PR that gets merged will automatically be made available on the MyGet, and once the PR has got more quality testing it gets promoted to nuget.org

**Comment by gsgou** [comment]
Tks for the quick response @glennawatson, i appreciate it.
I will use myget as you are actively working on this project.
Is the same concept with the other reactiveui projects as well?

What github packages stand for?

**Comment by glennawatson** [comment]
GitHub packages we want to replace myget. There is a bug with them at the moment where they generate a GitHub release any time you push a nuget package to them. Been talking to project manager in that team and it's high on their priority list. In terms of the feed it's all our packages yep n

**Comment by gsgou** [comment]
Got it thanks a lot.
I will use both until i notice that you switched to github packages.

**Comment by glennawatson** [comment]
I'll do a blog post when the swap is available
