### ISSUE TITLE
feature: add support for UWP navigation

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/Sextant#45]
**Is your feature request related to a problem? Please describe.**
There is no support for UWP native currently.

**Describe the solution you'd like**
Please add support for the UWP navigation stack.

**Comment by weitzhandler** [comment]
We need to split up Sextant and take out the core features to an abstracted platform-independent `Sextant.Core` package. I'm willing to do this. Can I PR? Any guidance?

**Comment by glennawatson** [comment]
Talk to @RLittlesII  on slack see where he needs the help. He and @giusepe  are in charge of the sextant project.

**Comment by RLittlesII** [comment]
Thanks @limefrogyank for tackling this feature.
