### ISSUE TITLE
[BUG] Type resolver error when running Sextant 1.6 with Xamarin.Forms

### ISSUE THREAD

**Issue by giusepe** [reactiveui/Sextant#54]
**Describe the bug**

After creating a new project with Xamarin.Forms and Sextant 1.6 I get this error
```Could not resolve type with token 01000005 from typeref (expected class 'Sextant.SextantHelper' in assembly 'Sextant, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null')```

If I downgrade to 1.5.5 everything works. 

**Steps To Reproduce**

@RLittlesII already created a sample that shows the issue: https://github.com/RLittlesII/Sextant.Sample

**Expected behavior**

No errors :)

**Screenshots**

**Environment**

- OS:       
- Version   
- Device:   

**Additional context**

**Comment by RLittlesII** [comment]
@giusepe I did some digging around and tried to mess with some of the multitargeting stuff.  I am going to do some additional research.  I am pretty sure that resolving #51 will most likely resolve this issue.  I'd like to see if we can do it without going to that length if possible.
