### ISSUE TITLE
[BUG] PushModal does not allways show View

### ISSUE THREAD

**Issue by Flying--Dutchman** [reactiveui/Sextant#544]
**Describe the bug**

From our users we get the info that sometimes the modal views aren't being pushed onto the stack. As in, calling the modal view doesn't seem to do anything. We were able to reproduce the issue only once and that without any exception.
It's very strange since it does happen on multiple devices, mostly older devices, but only on very rare occasions and after a new start of the app everything is working fine. 

We also received the info that one user experienced the bug that, although the called modal view isn't visible, the app appears unresponsive.

I know this isn't much information, but maybe someone has experienced the same, or someone has any idea or hint why this happens.

**Comment by RLittlesII** [comment]
@Flying--Dutchman If you can provide a reproduction, or maybe even a code snippet showing how you are consuming it, it would definitely help.

Also.  Some of the information in the bug template is useful to understand your particular problem, i.e.

**Environment**

- OS:       
- Device:   
- Version:   
- Working Version:

**Comment by Flying--Dutchman** [comment]
We currently only have Android builds; The bug appeared on different Samsung devices and a Pixel C tablet.
We're calling the new ViewModel with:

```
ReactiveCommand.CreateFromObservable( () => ViewStackService.PushModal<PlaceholderViewViewModel>());
```

Version:
Xamarin.Forms: 5.0.0.2012
ReactiveUI.XamForms: 13.3.2
Sextant.XamForms: 2.12.4

**Comment by RLittlesII** [comment]
@Flying--Dutchman Did you try adding an output scheduler to the `ReactiveCommand.CreateFromObservable`?

**Comment by Flying--Dutchman** [comment]
I'm very sorry. Did just write my bachelor thesis and had zero time for my app. 
I will test next week with adding an output scheduler. Thank you

**Comment by Flying--Dutchman** [comment]
As it seems we are currently unable to reproduce this issue, even without an output scheduler. 
I'll keep an eye out and report back if it happens again.

Thank you for your help :+1:
