### ISSUE TITLE
[BUG] In Xamarin Forms the iOS dll is loaded instead of the .netstandard (version 1.6.1)

### ISSUE THREAD

**Issue by gsgou** [reactiveui/Sextant#77]
**Describe the bug**

package 1.5.5 works as expected in iOS

package 1.6.1 with Linker behavior (Link Framework SDK's only)
Fails to build
MTOUCH : error MT2101: Can't resolve the reference 'Sextant.NavigationView Sextant.SextantHelper::Initialize(System.Reactive.Concurrency.IScheduler,System.Reactive.Concurrency.IScheduler,ReactiveUI.IViewLocator)', referenced from the method 'System.Void XXX.App::.ctor()' in 'Sextant, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null'.

package 1.6.1 with Linker behavior (Don't Link)
Crashes on Startup with  System.TypeLoadException has been thrown Sextant.SextantHelper

The iOS dll is getting loaded instead of the .netstandard also if configured:
```xml
  <ItemGroup>
    <Reference Include="Sextant">
      <HintPath>$(NugetPackagesPath)\sextant\1.6.1\lib\netstandard2.0\Sextant.dll</HintPath>
    </Reference>
  </ItemGroup>
```

**Environment**

- OS: iOS
- Version: 12.2
- Device: Any device, or simulator

**Comment by RLittlesII** [comment]
@gsgou This was documented https://github.com/reactiveui/Sextant/issues/54 and resolved https://github.com/reactiveui/Sextant/pull/62

I am trying to get a 2.0 release out to resolve this, in the mean time you can use the packages from the [GitHub Packages](https://github.com/orgs/reactiveui/packages?utf8=%E2%9C%93&q=Sextant) 

I believe 1.7.3 should have all the required bits.

**Comment by gsgou** [comment]
Thanks a lot. Great job, moving from Xamvvm with all the effort and features adding I see.

**Comment by RLittlesII** [comment]
I unlisted the 1.6.1 package from nuget.  That should alleviate anyone else running into this issue until we ship 2.0

Thanks for the report.
