### ISSUE TITLE
Option to wrap a modal inside a NavigationPage

### ISSUE THREAD

**Issue by modplug** [reactiveui/Sextant#98]
When I do PushModal from my viewmodel, the modal shows just fine. But as a good citizen I added a "Close" Toolbar button in the top right corner so that the user can opt out of the modal. The button is never shown because the modal doesn't have a NavigationPage.

I've used similiar frameworks before and I think MvvmCross has an option to "WrapInNavigationPage" when pushing modals.

An alternate solution would perhaps be to do this by using interactions, but that might trick the IViewStackService

There should be an option to wrap it in a NavigationPage.

**Additional context**

Screenshot nr 2 is the modal page without the NavigationBar.

![Screenshot 2019-07-12 at 11 32 07](https://user-images.githubusercontent.com/789588/61118317-c5add980-a498-11e9-9e6b-46c6b28af32b.png)
![Screenshot 2019-07-12 at 11 32 26](https://user-images.githubusercontent.com/789588/61118324-c7779d00-a498-11e9-9f93-56b7f1a6c1b2.png)

**Comment by giusepe** [comment]
Possibly a regression caused by #96 or even earlier in the 1.7.*
I tested with the version 1.5.5 and works as intended, but the view/viewmodel registration is different.

Thanks for trying the bleeding edge version and reporting the bug, just a heads up that version 1.7.* is a WIP that will become 2.0 and more suitable for production.

**Comment by RLittlesII** [comment]
@modplug I think I found the issue going to do a bit of checking around and verify that I haven't broken anything else.  It was a regression issue with how we are registering the `NavigationView`. 
👍 @giusepe for that thought.

**Comment by RLittlesII** [comment]
@modplug If you get the chance can you pull the beta bits and verify this solves your problem?
